### ISSUE TITLE
[Bug] The user who quits the game is the one to win

### ISSUE THREAD

**Issue by llescure** [cnstll/ft_transcendAnce#143]
### Describe the bug

When a user unexpectedly quit the game, his score is set to 10 and he wins the match.

### Steps to reproduce

1-Play a game between a user from the seed and your 42 profile
2-Close the tab with the 42 profile user
3-Go to the database, the user with your 42 profile has won and his score is set to 10

### Expected behavior

The user who unexpectedly quits the game should be the one to loose

### Environment

Desktop

### OS

macOs Monterey

### Browser

Chrome

### Version

107.0.5304.87

**Comment by COTHSC** [comment]
This is a Feature:

Ne m'est-il pas permis de faire de mon bien ce que je veux? Ou vois-tu de mauvais oeil que je sois bon? - Ainsi les derniers seront les premiers, et les premiers seront les derniers.

Evangile de Jésus-Christ selon saint Matthieu 20
