### ISSUE TITLE
[Bug] The ball and the paddle can go below the set dimension of the window

### ISSUE THREAD

**Issue by llescure** [cnstll/ft_transcendAnce#155]
### Describe the bug

The ball and the paddle can be hidden and can go below the set dimension of the canvas

### Steps to reproduce

1-Launch a game between 2 players
2-Move the paddle with your mouse on the far right corner

### Expected behavior

The paddle and the ball shouldn't be able to go below the set dimension of the window

### Environment

Desktop

### OS

macOS Monterey

### Browser

Chrome

### Version

107.0.5304.87

**Comment by COTHSC** [comment]
fixed in other issue
