### ISSUE TITLE
[Bug] Have a status error on 42 login

### ISSUE THREAD

**Issue by llescure** [cnstll/ft_transcendAnce#231]
### Describe the bug

We have a prisma error on user status when we log in with 42

### Steps to reproduce

1-Go to the sign-in page
2-Sign in with 42
3-You get a prisma error
![Uploading Screenshot 2022-11-23 at 15.51.46.png…]()

### Expected behavior

We should not get any error and see the home page

**Comment by cnstll** [comment]
Linked to socket disconnecting on sign in page while user does not have a userId yet

**Comment by cnstll** [comment]
Fixed in issue #40
