### ISSUE TITLE
[Bug] When second player leaves the game, there is an issue

### ISSUE THREAD

**Issue by estelle-rcr** [cnstll/ft_transcendAnce#235]
### Describe the bug

When player 1 leaves, player 2 is waiting. If he leaves, then he can rejoin the game and the game plays again without the opponent.

If the player 2 leaves, the waiting list is canceled and the game is deleted (no score)

### Steps to reproduce

When player 1 leaves, player 2 is waiting. If he leaves, then he can rejoin the game and the game plays again without the opponent.

### Expected behavior

see above

**Comment by cnstll** [comment]
Fixed by @COTHSC
