### ISSUE TITLE
[US] As a user, I want to consult the general ranking of players

### ISSUE THREAD

**Issue by estelle-rcr** [cnstll/ft_transcendAnce#25]
### User Story

As a user,
I want to consult the ranking of all players,
so that I can see how I rank against other players.

### Expected Behavior / Acceptance criteria

When I play, my rank is updated according to my Elo score.
When I haven't played yet, my Elo score is 0 and I'm ranked ex aequo with all other not playing users
When two players have the Elo score, they're ranked ex aequo 
When players are ex aequo, they're ranked by alphabetical order (simpler than the oldest record being first ?)

**Comment by llescure** [comment]
Not done
