### ISSUE TITLE
[Bug] Sending a DM and blocking the user inside it doesn't delete the DM

### ISSUE THREAD

**Issue by llescure** [cnstll/ft_transcendAnce#316]
### Describe the bug

Sending a DM to a user2 and blocking user2 inside the chat DM doesn't delete the user

### Steps to reproduce

1-Go to chat
2-DM a user
3-Block the user with whom you have the DM
4-The DM is not deleted

### Expected behavior

The DM should be deleted and the user should be redirected to the next channel

### Browser

None

**Comment by cnstll** [comment]
merged
